-- MySQL Script generated by MySQL Workbench
-- jue 23 jun 2022 23:45:24
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bank` DEFAULT CHARACTER SET utf8 ;
USE `bank` ;

-- -----------------------------------------------------
-- Table `mydb`.`PERSONA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank`.`PERSONA` (
                                                `IDPERSONA` INT NOT NULL AUTO_INCREMENT,
                                                `NOMBRE` VARCHAR(60) NOT NULL,
    `GENERO` VARCHAR(20) NOT NULL,
    `IDENTIFICACION` VARCHAR(13) NOT NULL,
    `DIRECCION` VARCHAR(200) NULL,
    `TELEFONO` VARCHAR(10) NULL,
    `EDAD` INT NULL,
    PRIMARY KEY (`IDPERSONA`),
    UNIQUE INDEX `IDENTIFICACION_UNIQUE` (`IDENTIFICACION` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank`.`CLIENTE` (
                                                `IDCLIENTE` INT NOT NULL AUTO_INCREMENT,
                                                `PASSWORD` VARCHAR(45) NOT NULL,
    `STATUS` VARCHAR(1) NOT NULL,
    `IDPERSONA` INT NOT NULL,
    PRIMARY KEY (`IDCLIENTE`),
    INDEX `fk_CLIENTE_PERSONA_idx` (`IDPERSONA` ASC) VISIBLE,
    CONSTRAINT `fk_CLIENTE_PERSONA`
    FOREIGN KEY (`IDPERSONA`)
    REFERENCES `bank`.`PERSONA` (`IDPERSONA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CUENTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank`.`CUENTA` (
                                               `IDCUENTA` INT NOT NULL AUTO_INCREMENT,
                                               `NUMERO` VARCHAR(25) NOT NULL,
    `TIPOCUENTA` VARCHAR(45) NOT NULL,
    `SALDOINICIAL` DECIMAL(18,4) NOT NULL,
    `ESTADO` VARCHAR(1) NOT NULL,
    `IDCLIENTE` INT NOT NULL,
    PRIMARY KEY (`IDCUENTA`),
    INDEX `fk_CUENTA_CLIENTE1_idx` (`IDCLIENTE` ASC) VISIBLE,
    CONSTRAINT `fk_CUENTA_CLIENTE1`
    FOREIGN KEY (`IDCLIENTE`)
    REFERENCES `bank`.`CLIENTE` (`IDCLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`MOVIMIENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank`.`MOVIMIENTO` (
                                                   `IDMOVIMIENTO` INT NOT NULL AUTO_INCREMENT,
                                                   `FECHA` DATETIME NOT NULL,
                                                   `TIPOMOVIMIENTO` VARCHAR(30) NOT NULL,
                                                   `VALOR` DECIMAL(18,4) NOT NULL,
    `SALDO` DECIMAL(18,4) NOT NULL,
    `IDCUENTA` INT NOT NULL,
    PRIMARY KEY (`IDMOVIMIENTO`),
    INDEX `fk_MOVIMIENTO_CUENTA1_idx` (`IDCUENTA` ASC) VISIBLE,
    CONSTRAINT `fk_MOVIMIENTO_CUENTA1`
    FOREIGN KEY (`IDCUENTA`)
    REFERENCES `bank`.`CUENTA` (`IDCUENTA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
